scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # basic tests configured to test CRs
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml"
    # olm tests configured to test CRs
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_platformapi_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-platform-api-operator/3.6.0/ibm-platform-api-operator.v3.6.0.clusterserviceversion.yaml"
