apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: ibm-platform-api-operator
  name: ibm-platform-api-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ibm-platform-api-operator
  template:
    metadata:
      annotations:
        productID: 068a62892a1e4db39641342e592daa25
        productMetric: FREE
        productName: IBM Cloud Platform Common Services
      labels:
        app.kubernetes.io/instance: platform-api
        app.kubernetes.io/managed-by: platformapis.operator.ibm.com
        app.kubernetes.io/name: platformapis.operator.ibm.com
        name: ibm-platform-api-operator
    spec:
      containers:
      - args:
        - "--enable-leader-election"
        - "--leader-election-id=ibm-platform-api-operator"
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: AUDIT_SYSLOG_SERVICE_IMAGE
          value: "quay.io/opencloudio/audit-syslog-service:1.0.7"
        - name: ICP_PLATFORM_API_IMAGE
          value: "quay.io/opencloudio/icp-platform-api:3.8.0"
        - name: KUBECTL_IMAGE
          value: quay.io/opencloudio/kubectl:v1.15.9.7
        image: "quay.io/opencloudio/ibm-platform-api-operator:latest"
        imagePullPolicy: Always
        name: ibm-platform-api-operator
        resources:
          limits:
            cpu: 100m
            memory: 800Mi
          requests:
            cpu: 30m
            memory: 300Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          privileged: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      serviceAccountName: ibm-platform-api-operator