---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.platformApi.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name:  {{ .Values.platformApi.name }}
    helm.sh/chart: {{ .Release.Name }}
  name: "{{ .Values.platformApi.name }}"
spec:
  type: ClusterIP
  ports:
    - port: 6969
      targetPort: 6969
  selector:
    k8s-app: "{{ .Values.platformApi.name }}"
    release: {{ .Release.Name }}