apiVersion: v1
appVersion: 4.1.0.0-000000
description: ICP Platform API Service
keywords:
  - kubernetes
  - IBM Cloud Private
  - API
  - IcpClusterResource
  - s390x
  - ppc64le
  - amd64
  - ICP
  - Development
  - Commercial
kubeVersion: '>=1.11.0-0'
tillerVersion: '>=2.16.1'
maintainers:
  - email: icpapi@us.ibm.com
    name: IBM Cloud Private
name: platform-api
version: 3.7.1
